services:
  mysql:
    image: mysql:9.0.1
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      SCHEMA_KC: ${SCHEMA_KC}
      SCHEMA_KC_USER: ${SCHEMA_KC_USER}
      SCHEMA_KC_PASSWORD: ${SCHEMA_KC_PASSWORD}
      SCHEMA_APP: ${SCHEMA_APP}
      SCHEMA_APP_USER: ${SCHEMA_APP_USER}
      SCHEMA_APP_PASSWORD: ${SCHEMA_APP_PASSWORD}
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/a.sh
      - ./health-check.sh:/usr/local/bin/health_check.sh
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    healthcheck:
      test: [ "CMD", "/usr/local/bin/health_check.sh" ]
      interval: 10s
      timeout: 10s
      retries: 5


  keycloak_web:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: ${KC_CONTAINER_NAME}
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS}
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: ${KC_HTTP_PORT}
    command: start-dev
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - ${KC_HTTP_PORT}:${KC_HTTP_PORT}