#!/bin/bash
mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" <<EOSQL
  CREATE DATABASE IF NOT EXISTS $SCHEMA_KC;
  CREATE USER IF NOT EXISTS '$SCHEMA_KC_USER'@'%' IDENTIFIED BY '$SCHEMA_KC_PASSWORD';
  GRANT ALL PRIVILEGES ON $SCHEMA_KC.* TO '$SCHEMA_KC_USER'@'%';

  CREATE DATABASE IF NOT EXISTS $SCHEMA_APP;
  CREATE USER IF NOT EXISTS '$SCHEMA_APP_USER'@'%' IDENTIFIED BY '$SCHEMA_APP_PASSWORD';
  GRANT ALL PRIVILEGES ON $SCHEMA_APP.* TO '$SCHEMA_APP_USER'@'%';

  FLUSH PRIVILEGES;
EOSQL